"""SAP S/4HANA standard module knowledge base.

Each module contains standard functions used for Fit/Gap analysis matching.
Structured as: module_id -> {name, name_ja, description, standard_functions[]}.
Each standard_function has: id, name, name_ja, description, t_codes[], category.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# SD - Sales and Distribution (販売管理)
# ---------------------------------------------------------------------------
SD_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "SD-001", "name": "Inquiry Management", "name_ja": "引合管理",
     "description": "Create and manage customer inquiries",
     "t_codes": ["VA11", "VA12", "VA13"], "category": "pre-sales"},
    {"id": "SD-002", "name": "Quotation Management", "name_ja": "見積管理",
     "description": "Create, change, display quotations",
     "t_codes": ["VA21", "VA22", "VA23"], "category": "pre-sales"},
    {"id": "SD-003", "name": "Sales Order Processing", "name_ja": "受注処理",
     "description": "Standard sales order creation and processing",
     "t_codes": ["VA01", "VA02", "VA03"], "category": "order"},
    {"id": "SD-004", "name": "Sales Order Types", "name_ja": "受注タイプ",
     "description": "Standard order, rush order, cash sales, returns",
     "t_codes": ["VOV8"], "category": "order"},
    {"id": "SD-005", "name": "Pricing and Conditions", "name_ja": "価格設定・条件管理",
     "description": "Condition technique for pricing, surcharges, discounts",
     "t_codes": ["VK11", "VK12", "VK13"], "category": "pricing"},
    {"id": "SD-006", "name": "Free Goods Determination", "name_ja": "無償品決定",
     "description": "Automatic free goods in sales orders",
     "t_codes": ["VBN1"], "category": "pricing"},
    {"id": "SD-007", "name": "Credit Management", "name_ja": "与信管理",
     "description": "Automatic credit checks during order processing",
     "t_codes": ["FD32", "UKM_BP"], "category": "credit"},
    {"id": "SD-008", "name": "Availability Check (ATP)", "name_ja": "在庫引当チェック",
     "description": "Available-to-promise check during order entry",
     "t_codes": ["CO09", "MD04"], "category": "order"},
    {"id": "SD-009", "name": "Delivery Processing", "name_ja": "出荷処理",
     "description": "Outbound delivery creation and processing",
     "t_codes": ["VL01N", "VL02N", "VL03N"], "category": "shipping"},
    {"id": "SD-010", "name": "Picking and Packing", "name_ja": "ピッキング・梱包",
     "description": "Warehouse picking and packing for deliveries",
     "t_codes": ["VL02N"], "category": "shipping"},
    {"id": "SD-011", "name": "Goods Issue for Delivery", "name_ja": "出庫転記",
     "description": "Post goods issue for outbound deliveries",
     "t_codes": ["VL02N"], "category": "shipping"},
    {"id": "SD-012", "name": "Shipping Point Determination", "name_ja": "出荷ポイント決定",
     "description": "Automatic shipping point determination",
     "t_codes": ["OVL2"], "category": "shipping"},
    {"id": "SD-013", "name": "Route Determination", "name_ja": "ルート決定",
     "description": "Automatic transportation route determination",
     "t_codes": ["0VTC"], "category": "shipping"},
    {"id": "SD-014", "name": "Billing Document Processing", "name_ja": "請求書処理",
     "description": "Invoice, credit memo, debit memo creation",
     "t_codes": ["VF01", "VF02", "VF03"], "category": "billing"},
    {"id": "SD-015", "name": "Billing Plan", "name_ja": "請求プラン",
     "description": "Periodic billing and milestone billing",
     "t_codes": ["VF01"], "category": "billing"},
    {"id": "SD-016", "name": "Output Management", "name_ja": "帳票管理",
     "description": "Order confirmations, delivery notes, invoices output",
     "t_codes": ["NACE", "VV31"], "category": "output"},
    {"id": "SD-017", "name": "Returns Processing", "name_ja": "返品処理",
     "description": "Customer returns and credit memo processing",
     "t_codes": ["VA01"], "category": "returns"},
    {"id": "SD-018", "name": "Rebate Processing", "name_ja": "リベート処理",
     "description": "Volume-based rebate agreements",
     "t_codes": ["VB01", "VB02"], "category": "pricing"},
    {"id": "SD-019", "name": "Third-Party Order Processing", "name_ja": "直送処理",
     "description": "Drop shipment / third-party order processing",
     "t_codes": ["VA01", "ME21N"], "category": "order"},
    {"id": "SD-020", "name": "Intercompany Sales", "name_ja": "会社間取引",
     "description": "Intercompany sales and billing",
     "t_codes": ["VA01", "VF01"], "category": "order"},
    {"id": "SD-021", "name": "Consignment Processing", "name_ja": "委託販売",
     "description": "Consignment fill-up, issue, pickup, returns",
     "t_codes": ["VA01"], "category": "order"},
    {"id": "SD-022", "name": "Foreign Trade", "name_ja": "外国貿易",
     "description": "Export/import processing, trade compliance",
     "t_codes": ["VX11N"], "category": "trade"},
    {"id": "SD-023", "name": "Sales Reporting", "name_ja": "販売レポート",
     "description": "Standard sales analytics and reporting",
     "t_codes": ["VF45N", "VA05"], "category": "reporting"},
    {"id": "SD-024", "name": "Partner Determination", "name_ja": "取引先機能決定",
     "description": "Automatic partner determination in sales documents",
     "t_codes": ["VOPAN"], "category": "master-data"},
    {"id": "SD-025", "name": "Material Determination", "name_ja": "品目決定",
     "description": "Automatic material substitution in orders",
     "t_codes": ["VB11"], "category": "order"},
]

# ---------------------------------------------------------------------------
# MM - Materials Management (在庫/購買管理)
# ---------------------------------------------------------------------------
MM_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "MM-001", "name": "Purchase Requisition", "name_ja": "購買依頼",
     "description": "Create and manage purchase requisitions",
     "t_codes": ["ME51N", "ME52N", "ME53N"], "category": "procurement"},
    {"id": "MM-002", "name": "Purchase Order Processing", "name_ja": "発注処理",
     "description": "Create, change, display purchase orders",
     "t_codes": ["ME21N", "ME22N", "ME23N"], "category": "procurement"},
    {"id": "MM-003", "name": "Request for Quotation (RFQ)", "name_ja": "見積依頼",
     "description": "Manage supplier quotations",
     "t_codes": ["ME41", "ME42", "ME47"], "category": "procurement"},
    {"id": "MM-004", "name": "Source Determination", "name_ja": "ソース決定",
     "description": "Source list and quota arrangement",
     "t_codes": ["ME01", "MEQ1"], "category": "procurement"},
    {"id": "MM-005", "name": "Outline Agreement (Contract)", "name_ja": "基本契約",
     "description": "Quantity and value contracts with vendors",
     "t_codes": ["ME31K", "ME31L"], "category": "procurement"},
    {"id": "MM-006", "name": "Scheduling Agreement", "name_ja": "分納契約",
     "description": "Long-term scheduling agreements",
     "t_codes": ["ME31L"], "category": "procurement"},
    {"id": "MM-007", "name": "Goods Receipt", "name_ja": "入庫処理",
     "description": "Goods receipt against PO, production, others",
     "t_codes": ["MIGO"], "category": "inventory"},
    {"id": "MM-008", "name": "Goods Issue", "name_ja": "出庫処理",
     "description": "Goods issue for consumption, scrap, etc.",
     "t_codes": ["MIGO"], "category": "inventory"},
    {"id": "MM-009", "name": "Stock Transfer / Transfer Posting", "name_ja": "在庫転送・転記",
     "description": "Transfer between plants, storage locations",
     "t_codes": ["MIGO", "MB1B"], "category": "inventory"},
    {"id": "MM-010", "name": "Physical Inventory", "name_ja": "棚卸",
     "description": "Physical inventory count and adjustment",
     "t_codes": ["MI01", "MI04", "MI07"], "category": "inventory"},
    {"id": "MM-011", "name": "Invoice Verification", "name_ja": "請求照合",
     "description": "Logistics invoice verification",
     "t_codes": ["MIRO"], "category": "invoice"},
    {"id": "MM-012", "name": "Evaluated Receipt Settlement (ERS)", "name_ja": "検収決済",
     "description": "Automatic settlement without invoice",
     "t_codes": ["MRRL"], "category": "invoice"},
    {"id": "MM-013", "name": "Material Valuation", "name_ja": "品目評価",
     "description": "Standard price, moving average price",
     "t_codes": ["MR21", "MR22"], "category": "valuation"},
    {"id": "MM-014", "name": "Batch Management", "name_ja": "ロット管理",
     "description": "Batch tracking and batch determination",
     "t_codes": ["MSC1N", "MSC2N"], "category": "inventory"},
    {"id": "MM-015", "name": "Serial Number Management", "name_ja": "シリアル番号管理",
     "description": "Individual item tracking with serial numbers",
     "t_codes": ["IQ01"], "category": "inventory"},
    {"id": "MM-016", "name": "Reservation", "name_ja": "予約",
     "description": "Material reservations for planned usage",
     "t_codes": ["MB21", "MB22"], "category": "inventory"},
    {"id": "MM-017", "name": "Material Master Management", "name_ja": "品目マスタ管理",
     "description": "Create and maintain material master data",
     "t_codes": ["MM01", "MM02", "MM03"], "category": "master-data"},
    {"id": "MM-018", "name": "Vendor Master Management", "name_ja": "仕入先マスタ管理",
     "description": "Create and maintain vendor master data",
     "t_codes": ["BP", "XK01", "XK02"], "category": "master-data"},
    {"id": "MM-019", "name": "Automatic PO Generation", "name_ja": "自動発注",
     "description": "MRP-driven automatic purchase order creation",
     "t_codes": ["ME59N"], "category": "procurement"},
    {"id": "MM-020", "name": "Purchasing Reports", "name_ja": "購買レポート",
     "description": "Purchase order history, vendor evaluation",
     "t_codes": ["ME2M", "ME2N", "ME80FN"], "category": "reporting"},
    {"id": "MM-021", "name": "Consignment from Vendor", "name_ja": "仕入先寄託品",
     "description": "Vendor consignment stock management",
     "t_codes": ["ME21N"], "category": "procurement"},
    {"id": "MM-022", "name": "Subcontracting", "name_ja": "外注加工",
     "description": "Subcontracting purchase orders with component provision",
     "t_codes": ["ME21N"], "category": "procurement"},
    {"id": "MM-023", "name": "Service Procurement", "name_ja": "サービス調達",
     "description": "Service entry sheets and service POs",
     "t_codes": ["ML81N"], "category": "procurement"},
    {"id": "MM-024", "name": "Release Strategy", "name_ja": "承認戦略",
     "description": "Approval workflow for purchase requisitions and POs",
     "t_codes": ["ME28", "ME29N"], "category": "procurement"},
    {"id": "MM-025", "name": "Vendor Evaluation", "name_ja": "仕入先評価",
     "description": "Automatic vendor scoring and evaluation",
     "t_codes": ["ME61"], "category": "reporting"},
]

# ---------------------------------------------------------------------------
# FI - Financial Accounting (財務会計)
# ---------------------------------------------------------------------------
FI_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "FI-001", "name": "General Ledger Posting", "name_ja": "総勘定元帳転記",
     "description": "Journal entries and GL postings",
     "t_codes": ["FB50", "FB01", "F-02"], "category": "gl"},
    {"id": "FI-002", "name": "Document Parking", "name_ja": "仮登録",
     "description": "Park and post documents with approval",
     "t_codes": ["FBV0", "FBV2"], "category": "gl"},
    {"id": "FI-003", "name": "Recurring Entries", "name_ja": "繰返転記",
     "description": "Automatic recurring journal entries",
     "t_codes": ["FBD1", "F.14"], "category": "gl"},
    {"id": "FI-004", "name": "Accounts Payable Invoice", "name_ja": "買掛金管理",
     "description": "Vendor invoice posting and management",
     "t_codes": ["FB60", "FBL1N"], "category": "ap"},
    {"id": "FI-005", "name": "AP Payment Processing", "name_ja": "支払処理",
     "description": "Automatic payment program and manual payments",
     "t_codes": ["F110", "F-53"], "category": "ap"},
    {"id": "FI-006", "name": "Accounts Receivable Invoice", "name_ja": "売掛金管理",
     "description": "Customer invoice posting and management",
     "t_codes": ["FB70", "FBL5N"], "category": "ar"},
    {"id": "FI-007", "name": "AR Payment / Incoming Payment", "name_ja": "入金処理",
     "description": "Incoming payment processing and clearing",
     "t_codes": ["F-28", "F-32"], "category": "ar"},
    {"id": "FI-008", "name": "Dunning", "name_ja": "督促管理",
     "description": "Automatic dunning notice creation",
     "t_codes": ["F150"], "category": "ar"},
    {"id": "FI-009", "name": "Bank Accounting", "name_ja": "銀行会計",
     "description": "Bank statement processing and reconciliation",
     "t_codes": ["FF67", "FEBAN"], "category": "bank"},
    {"id": "FI-010", "name": "Electronic Bank Statement", "name_ja": "電子口座明細",
     "description": "Automatic bank statement import and posting",
     "t_codes": ["FEBAN", "FF_5"], "category": "bank"},
    {"id": "FI-011", "name": "Cash Journal", "name_ja": "現金出納帳",
     "description": "Petty cash management",
     "t_codes": ["FBCJ"], "category": "bank"},
    {"id": "FI-012", "name": "Fixed Asset Acquisition", "name_ja": "固定資産取得",
     "description": "Asset acquisition and capitalization",
     "t_codes": ["F-90", "ABZON"], "category": "asset"},
    {"id": "FI-013", "name": "Asset Depreciation", "name_ja": "減価償却",
     "description": "Depreciation calculation and posting",
     "t_codes": ["AFAB"], "category": "asset"},
    {"id": "FI-014", "name": "Asset Retirement", "name_ja": "固定資産除却",
     "description": "Asset sale, scrapping, retirement",
     "t_codes": ["ABAON", "ABAVN"], "category": "asset"},
    {"id": "FI-015", "name": "Asset Transfer", "name_ja": "資産移動",
     "description": "Transfer assets between cost centers",
     "t_codes": ["ABUMN"], "category": "asset"},
    {"id": "FI-016", "name": "Period-End Closing GL", "name_ja": "月次決算(GL)",
     "description": "Foreign currency revaluation, accruals, reclassification",
     "t_codes": ["FAGL_FC_VAL", "FBS1"], "category": "closing"},
    {"id": "FI-017", "name": "Year-End Closing", "name_ja": "年次決算",
     "description": "Balance carryforward, year-end adjustments",
     "t_codes": ["FAGLGVTR"], "category": "closing"},
    {"id": "FI-018", "name": "Financial Statements", "name_ja": "財務諸表",
     "description": "Balance sheet, P&L, trial balance reporting",
     "t_codes": ["S_ALR_87012284", "FAGLB03"], "category": "reporting"},
    {"id": "FI-019", "name": "Tax Processing", "name_ja": "税務処理",
     "description": "Tax calculation, tax reporting, withholding tax",
     "t_codes": ["S_ALR_87012357"], "category": "tax"},
    {"id": "FI-020", "name": "Intercompany Accounting", "name_ja": "会社間会計",
     "description": "Intercompany postings and reconciliation",
     "t_codes": ["FBU8", "FB01"], "category": "gl"},
    {"id": "FI-021", "name": "Chart of Accounts Management", "name_ja": "勘定科目表管理",
     "description": "GL account master data management",
     "t_codes": ["FS00", "FSP0"], "category": "master-data"},
    {"id": "FI-022", "name": "Cost Element Accounting", "name_ja": "原価要素管理",
     "description": "Primary and secondary cost element management",
     "t_codes": ["KA01", "KA02"], "category": "master-data"},
    {"id": "FI-023", "name": "Document Reversal", "name_ja": "伝票取消",
     "description": "Reverse posted documents",
     "t_codes": ["FB08", "FBRA"], "category": "gl"},
    {"id": "FI-024", "name": "GR/IR Clearing", "name_ja": "GR/IR消込",
     "description": "Goods receipt / invoice receipt clearing",
     "t_codes": ["F.13", "MR11"], "category": "closing"},
    {"id": "FI-025", "name": "Payment Terms Management", "name_ja": "支払条件管理",
     "description": "Define and manage payment terms",
     "t_codes": ["OBB8"], "category": "master-data"},
]

# ---------------------------------------------------------------------------
# CO - Controlling (管理会計)
# ---------------------------------------------------------------------------
CO_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "CO-001", "name": "Cost Center Accounting", "name_ja": "原価センター会計",
     "description": "Cost center planning, posting, reporting",
     "t_codes": ["KS01", "KS02", "KSB1"], "category": "cost-center"},
    {"id": "CO-002", "name": "Cost Center Planning", "name_ja": "原価センター計画",
     "description": "Budget planning per cost center",
     "t_codes": ["KP06", "KP26"], "category": "cost-center"},
    {"id": "CO-003", "name": "Internal Orders", "name_ja": "内部指図",
     "description": "Overhead cost orders, investment orders",
     "t_codes": ["KO01", "KO02", "KOB1"], "category": "internal-order"},
    {"id": "CO-004", "name": "Activity Type Planning", "name_ja": "活動タイプ計画",
     "description": "Define activity types and plan rates",
     "t_codes": ["KL01", "KP26"], "category": "cost-center"},
    {"id": "CO-005", "name": "Statistical Key Figures", "name_ja": "統計キー数値",
     "description": "Allocate costs based on statistical measures",
     "t_codes": ["KK01", "KB31N"], "category": "allocation"},
    {"id": "CO-006", "name": "Cost Distribution", "name_ja": "原価配分",
     "description": "Distribute costs across cost centers",
     "t_codes": ["KSV5"], "category": "allocation"},
    {"id": "CO-007", "name": "Cost Assessment", "name_ja": "原価振替",
     "description": "Assess costs to other cost objects",
     "t_codes": ["KSU5"], "category": "allocation"},
    {"id": "CO-008", "name": "Profit Center Accounting", "name_ja": "利益センター会計",
     "description": "Profit center planning and reporting",
     "t_codes": ["KE51", "KE5Z"], "category": "profit-center"},
    {"id": "CO-009", "name": "Profitability Analysis (CO-PA)", "name_ja": "収益性分析",
     "description": "Multi-dimensional profitability analysis",
     "t_codes": ["KE21N", "KE30"], "category": "copa"},
    {"id": "CO-010", "name": "Product Costing", "name_ja": "製品原価計算",
     "description": "Standard cost estimate, actual costing",
     "t_codes": ["CK11N", "CK40N"], "category": "product-cost"},
    {"id": "CO-011", "name": "Cost Object Controlling", "name_ja": "原価対象管理",
     "description": "Production order costing and variance analysis",
     "t_codes": ["KKB1"], "category": "product-cost"},
    {"id": "CO-012", "name": "Period-End Closing CO", "name_ja": "月次決算(CO)",
     "description": "Overhead calculation, WIP, settlement",
     "t_codes": ["KGI2", "KKAO", "KO88"], "category": "closing"},
    {"id": "CO-013", "name": "Budgeting / Funds Management", "name_ja": "予算管理",
     "description": "Budget allocation and availability control",
     "t_codes": ["KO22", "KBUD"], "category": "budget"},
    {"id": "CO-014", "name": "Transfer Pricing", "name_ja": "移転価格",
     "description": "Intercompany transfer pricing management",
     "t_codes": ["KE21N"], "category": "profit-center"},
    {"id": "CO-015", "name": "CO Reporting", "name_ja": "管理会計レポート",
     "description": "Standard CO reports and drilldown",
     "t_codes": ["S_ALR_87013611", "KSB1", "KOB1"], "category": "reporting"},
    {"id": "CO-016", "name": "Actual Costing / Material Ledger", "name_ja": "実際原価/品目元帳",
     "description": "Actual costing run and price determination",
     "t_codes": ["CKMLCP", "CKM3N"], "category": "product-cost"},
    {"id": "CO-017", "name": "Activity Allocation", "name_ja": "活動配賦",
     "description": "Direct and indirect activity allocation",
     "t_codes": ["KB21N"], "category": "allocation"},
    {"id": "CO-018", "name": "Overhead Calculation", "name_ja": "間接費計算",
     "description": "Apply overhead rates to cost objects",
     "t_codes": ["KGI2"], "category": "allocation"},
    {"id": "CO-019", "name": "Variance Analysis", "name_ja": "差異分析",
     "description": "Standard vs actual cost variance analysis",
     "t_codes": ["KKS1", "KKS2"], "category": "product-cost"},
    {"id": "CO-020", "name": "Settlement", "name_ja": "決済",
     "description": "Settle internal orders, projects to receivers",
     "t_codes": ["KO88", "CJ88"], "category": "closing"},
]

# ---------------------------------------------------------------------------
# PP - Production Planning (生産計画)
# ---------------------------------------------------------------------------
PP_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "PP-001", "name": "Demand Management", "name_ja": "需要管理",
     "description": "Planned independent requirements management",
     "t_codes": ["MD61", "MD62", "MD63"], "category": "demand"},
    {"id": "PP-002", "name": "MRP Run", "name_ja": "MRP実行",
     "description": "Material requirements planning execution",
     "t_codes": ["MD01", "MD02", "MD04"], "category": "mrp"},
    {"id": "PP-003", "name": "Planned Order Management", "name_ja": "計画手配管理",
     "description": "Create, change, convert planned orders",
     "t_codes": ["MD11", "MD12", "MD04"], "category": "mrp"},
    {"id": "PP-004", "name": "Production Order Creation", "name_ja": "製造指図作成",
     "description": "Create production orders from planned orders",
     "t_codes": ["CO01", "CO40", "CO41"], "category": "production"},
    {"id": "PP-005", "name": "Production Order Release", "name_ja": "製造指図リリース",
     "description": "Release production orders for execution",
     "t_codes": ["CO02"], "category": "production"},
    {"id": "PP-006", "name": "Goods Issue for Production", "name_ja": "製造向け出庫",
     "description": "Issue materials to production orders",
     "t_codes": ["MIGO", "MB1A"], "category": "production"},
    {"id": "PP-007", "name": "Confirmation (Completion)", "name_ja": "実績確認",
     "description": "Report production completion and quantities",
     "t_codes": ["CO11N", "CO15"], "category": "production"},
    {"id": "PP-008", "name": "Goods Receipt from Production", "name_ja": "製造入庫",
     "description": "Receive finished goods from production",
     "t_codes": ["MIGO", "MB31"], "category": "production"},
    {"id": "PP-009", "name": "BOM Management", "name_ja": "部品表管理",
     "description": "Bill of materials creation and maintenance",
     "t_codes": ["CS01", "CS02", "CS03"], "category": "master-data"},
    {"id": "PP-010", "name": "Routing Management", "name_ja": "作業手順管理",
     "description": "Production routing/recipe maintenance",
     "t_codes": ["CA01", "CA02", "CA03"], "category": "master-data"},
    {"id": "PP-011", "name": "Work Center Management", "name_ja": "作業区管理",
     "description": "Work center capacity and scheduling",
     "t_codes": ["CR01", "CR02", "CR03"], "category": "master-data"},
    {"id": "PP-012", "name": "Capacity Planning", "name_ja": "能力計画",
     "description": "Capacity evaluation and leveling",
     "t_codes": ["CM01", "CM07"], "category": "capacity"},
    {"id": "PP-013", "name": "Production Scheduling", "name_ja": "生産スケジューリング",
     "description": "Lead time scheduling and detailed scheduling",
     "t_codes": ["CM25"], "category": "capacity"},
    {"id": "PP-014", "name": "Repetitive Manufacturing", "name_ja": "繰返生産",
     "description": "High-volume repetitive manufacturing",
     "t_codes": ["MF50", "MFBF"], "category": "production"},
    {"id": "PP-015", "name": "Process Manufacturing", "name_ja": "プロセス製造",
     "description": "Recipe-based process manufacturing",
     "t_codes": ["C201", "COR1"], "category": "production"},
    {"id": "PP-016", "name": "Production Order Settlement", "name_ja": "製造指図決済",
     "description": "Settle production order costs",
     "t_codes": ["KO88", "CO88"], "category": "closing"},
    {"id": "PP-017", "name": "MRP Area", "name_ja": "MRPエリア",
     "description": "Sub-plant level MRP planning",
     "t_codes": ["MD01"], "category": "mrp"},
    {"id": "PP-018", "name": "Safety Stock Planning", "name_ja": "安全在庫計画",
     "description": "Safety stock and reorder point planning",
     "t_codes": ["MD02"], "category": "mrp"},
    {"id": "PP-019", "name": "Long-Term Planning (SOP)", "name_ja": "長期計画(SOP)",
     "description": "Sales and operations planning",
     "t_codes": ["MC87", "MC75"], "category": "demand"},
    {"id": "PP-020", "name": "Production Reporting", "name_ja": "生産レポート",
     "description": "Order status, capacity utilization reports",
     "t_codes": ["COOIS", "CM01"], "category": "reporting"},
]

# ---------------------------------------------------------------------------
# WM - Warehouse Management (倉庫管理)
# ---------------------------------------------------------------------------
WM_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "WM-001", "name": "Inbound Delivery Processing", "name_ja": "入荷処理",
     "description": "Inbound delivery and putaway",
     "t_codes": ["VL31N", "VL32N"], "category": "inbound"},
    {"id": "WM-002", "name": "Putaway Strategy", "name_ja": "格納戦略",
     "description": "Automatic bin determination for putaway",
     "t_codes": ["/SCWM/PRDI"], "category": "inbound"},
    {"id": "WM-003", "name": "Outbound Delivery / Picking", "name_ja": "出荷・ピッキング",
     "description": "Pick and ship outbound deliveries",
     "t_codes": ["VL01N", "VL02N"], "category": "outbound"},
    {"id": "WM-004", "name": "Warehouse Task Management", "name_ja": "倉庫タスク管理",
     "description": "Create and confirm warehouse tasks",
     "t_codes": ["/SCWM/MON"], "category": "execution"},
    {"id": "WM-005", "name": "Stock Overview", "name_ja": "在庫概要",
     "description": "Bin-level stock visibility",
     "t_codes": ["/SCWM/AQUA", "MMBE"], "category": "inventory"},
    {"id": "WM-006", "name": "Physical Inventory (WM)", "name_ja": "棚卸(倉庫管理)",
     "description": "Warehouse-level physical inventory",
     "t_codes": ["/SCWM/PI_MAIN"], "category": "inventory"},
    {"id": "WM-007", "name": "Internal Stock Transfer", "name_ja": "内部在庫移動",
     "description": "Bin-to-bin transfers within warehouse",
     "t_codes": ["/SCWM/ADGI"], "category": "execution"},
    {"id": "WM-008", "name": "Wave Management", "name_ja": "ウェーブ管理",
     "description": "Group outbound orders into waves",
     "t_codes": ["/SCWM/WAVE"], "category": "outbound"},
    {"id": "WM-009", "name": "Yard Management", "name_ja": "ヤード管理",
     "description": "Truck and dock door management",
     "t_codes": ["/SCWM/YM"], "category": "yard"},
    {"id": "WM-010", "name": "Slotting", "name_ja": "スロッティング",
     "description": "Optimize product placement in warehouse",
     "t_codes": ["/SCWM/SLOT"], "category": "optimization"},
    {"id": "WM-011", "name": "Resource Management", "name_ja": "リソース管理",
     "description": "Manage warehouse workers and equipment",
     "t_codes": ["/SCWM/RSRC"], "category": "execution"},
    {"id": "WM-012", "name": "Replenishment", "name_ja": "補充",
     "description": "Automatic bin replenishment",
     "t_codes": ["/SCWM/REPL"], "category": "optimization"},
    {"id": "WM-013", "name": "Returns Processing (WM)", "name_ja": "返品処理(倉庫)",
     "description": "Handle returns in warehouse",
     "t_codes": ["/SCWM/PRDI"], "category": "inbound"},
    {"id": "WM-014", "name": "Batch Management (WM)", "name_ja": "ロット管理(倉庫)",
     "description": "Batch tracking at bin level",
     "t_codes": ["/SCWM/AQUA"], "category": "inventory"},
    {"id": "WM-015", "name": "Dangerous Goods Management", "name_ja": "危険物管理",
     "description": "Hazardous material handling in warehouse",
     "t_codes": ["/SCWM/DGD"], "category": "compliance"},
    {"id": "WM-016", "name": "Quality Inspection (WM)", "name_ja": "品質検査(倉庫)",
     "description": "Quality check integration in warehouse",
     "t_codes": ["/SCWM/PRDI"], "category": "quality"},
    {"id": "WM-017", "name": "Cross-Docking", "name_ja": "クロスドッキング",
     "description": "Direct transfer from inbound to outbound",
     "t_codes": ["/SCWM/PRDI"], "category": "optimization"},
    {"id": "WM-018", "name": "Warehouse Monitoring", "name_ja": "倉庫モニタリング",
     "description": "Dashboard and KPI monitoring",
     "t_codes": ["/SCWM/MON"], "category": "reporting"},
    {"id": "WM-019", "name": "Kitting / VAS", "name_ja": "キッティング/付加価値サービス",
     "description": "Value-added services in warehouse",
     "t_codes": ["/SCWM/VAS"], "category": "execution"},
    {"id": "WM-020", "name": "RF / Mobile Device Support", "name_ja": "モバイルデバイス対応",
     "description": "Mobile device framework for warehouse",
     "t_codes": ["/SCWM/RFUI"], "category": "execution"},
]

# ---------------------------------------------------------------------------
# QM - Quality Management (品質管理)
# ---------------------------------------------------------------------------
QM_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "QM-001", "name": "Inspection Lot Creation", "name_ja": "検査ロット作成",
     "description": "Automatic/manual inspection lot creation",
     "t_codes": ["QA01", "QA02"], "category": "inspection"},
    {"id": "QM-002", "name": "Results Recording", "name_ja": "検査結果記録",
     "description": "Record inspection results and characteristics",
     "t_codes": ["QA32", "QE51N"], "category": "inspection"},
    {"id": "QM-003", "name": "Usage Decision", "name_ja": "使用決定",
     "description": "Accept, reject, or conditional release",
     "t_codes": ["QA11", "QA12"], "category": "inspection"},
    {"id": "QM-004", "name": "Quality Notification", "name_ja": "品質通知",
     "description": "Record defects, complaints, internal problems",
     "t_codes": ["QM01", "QM02"], "category": "notification"},
    {"id": "QM-005", "name": "Defect Recording", "name_ja": "不良記録",
     "description": "Catalog-based defect recording",
     "t_codes": ["QM01"], "category": "notification"},
    {"id": "QM-006", "name": "Corrective Action", "name_ja": "是正措置",
     "description": "Tasks and actions for quality issues",
     "t_codes": ["QM02"], "category": "notification"},
    {"id": "QM-007", "name": "Inspection Plan", "name_ja": "検査計画",
     "description": "Define inspection characteristics and methods",
     "t_codes": ["QP01", "QP02"], "category": "planning"},
    {"id": "QM-008", "name": "Material Specification", "name_ja": "品目仕様",
     "description": "Quality specifications for materials",
     "t_codes": ["QS21", "QS61"], "category": "planning"},
    {"id": "QM-009", "name": "Certificate Management", "name_ja": "証明書管理",
     "description": "Quality certificates for deliveries",
     "t_codes": ["QC01", "QC21"], "category": "certificate"},
    {"id": "QM-010", "name": "Vendor Quality (QM-PT)", "name_ja": "仕入先品質",
     "description": "Incoming inspection for vendor deliveries",
     "t_codes": ["QA01"], "category": "inspection"},
    {"id": "QM-011", "name": "In-Process Inspection", "name_ja": "工程内検査",
     "description": "Quality checks during production",
     "t_codes": ["QA01"], "category": "inspection"},
    {"id": "QM-012", "name": "Final Inspection", "name_ja": "最終検査",
     "description": "Finished goods inspection before delivery",
     "t_codes": ["QA01"], "category": "inspection"},
    {"id": "QM-013", "name": "Stability Study", "name_ja": "安定性試験",
     "description": "Long-term product stability tracking",
     "t_codes": ["QST01"], "category": "planning"},
    {"id": "QM-014", "name": "Control Chart", "name_ja": "管理図",
     "description": "Statistical process control charts",
     "t_codes": ["QGC1"], "category": "reporting"},
    {"id": "QM-015", "name": "Audit Management", "name_ja": "監査管理",
     "description": "Internal and external audit management",
     "t_codes": ["QM01"], "category": "audit"},
    {"id": "QM-016", "name": "Sample Management", "name_ja": "サンプル管理",
     "description": "Sample drawing and physical sample tracking",
     "t_codes": ["QPR5"], "category": "inspection"},
    {"id": "QM-017", "name": "Quality Score (Q-Score)", "name_ja": "品質スコア",
     "description": "Vendor and material quality scoring",
     "t_codes": ["QM19"], "category": "reporting"},
    {"id": "QM-018", "name": "Calibration Management", "name_ja": "校正管理",
     "description": "Test equipment calibration tracking",
     "t_codes": ["QE51N"], "category": "planning"},
    {"id": "QM-019", "name": "CAPA Management", "name_ja": "CAPA管理",
     "description": "Corrective and preventive action management",
     "t_codes": ["QM01"], "category": "notification"},
    {"id": "QM-020", "name": "Quality Reporting", "name_ja": "品質レポート",
     "description": "Standard quality analysis reports",
     "t_codes": ["QGA1", "QM10"], "category": "reporting"},
]

# ---------------------------------------------------------------------------
# PM - Plant Maintenance (プラント保全)
# ---------------------------------------------------------------------------
PM_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "PM-001", "name": "Equipment Master", "name_ja": "設備マスタ",
     "description": "Equipment and technical object management",
     "t_codes": ["IE01", "IE02", "IE03"], "category": "master-data"},
    {"id": "PM-002", "name": "Functional Location", "name_ja": "機能場所",
     "description": "Hierarchical location structure",
     "t_codes": ["IL01", "IL02"], "category": "master-data"},
    {"id": "PM-003", "name": "BOM for Maintenance", "name_ja": "保全BOM",
     "description": "Spare parts list for equipment",
     "t_codes": ["IB01", "IB02"], "category": "master-data"},
    {"id": "PM-004", "name": "Maintenance Notification", "name_ja": "保全通知",
     "description": "Report malfunctions and maintenance needs",
     "t_codes": ["IW21", "IW22"], "category": "notification"},
    {"id": "PM-005", "name": "Maintenance Order", "name_ja": "保全指図",
     "description": "Create and manage maintenance work orders",
     "t_codes": ["IW31", "IW32"], "category": "order"},
    {"id": "PM-006", "name": "Preventive Maintenance Plan", "name_ja": "予防保全計画",
     "description": "Time-based and performance-based maintenance",
     "t_codes": ["IP01", "IP02", "IP10"], "category": "planning"},
    {"id": "PM-007", "name": "Maintenance Scheduling", "name_ja": "保全スケジューリング",
     "description": "Schedule and dispatch maintenance tasks",
     "t_codes": ["IP10", "IP30"], "category": "planning"},
    {"id": "PM-008", "name": "Maintenance Confirmation", "name_ja": "保全実績確認",
     "description": "Report completed maintenance activities",
     "t_codes": ["IW41", "IW42"], "category": "execution"},
    {"id": "PM-009", "name": "Breakdown Maintenance", "name_ja": "事後保全",
     "description": "Reactive maintenance for unplanned failures",
     "t_codes": ["IW31"], "category": "order"},
    {"id": "PM-010", "name": "Condition-Based Maintenance", "name_ja": "状態基準保全",
     "description": "Maintenance triggered by measurement points",
     "t_codes": ["IK01", "IK11"], "category": "planning"},
    {"id": "PM-011", "name": "Maintenance Task List", "name_ja": "保全タスクリスト",
     "description": "Standard maintenance procedures",
     "t_codes": ["IA01", "IA02"], "category": "master-data"},
    {"id": "PM-012", "name": "Refurbishment", "name_ja": "修理品管理",
     "description": "Refurbish and return reusable parts",
     "t_codes": ["IW31"], "category": "order"},
    {"id": "PM-013", "name": "Maintenance History", "name_ja": "保全履歴",
     "description": "Track maintenance history per equipment",
     "t_codes": ["IW29", "IW69"], "category": "reporting"},
    {"id": "PM-014", "name": "Maintenance Costing", "name_ja": "保全コスト管理",
     "description": "Track maintenance costs per equipment/location",
     "t_codes": ["IW65"], "category": "reporting"},
    {"id": "PM-015", "name": "Warranty Management", "name_ja": "保証管理",
     "description": "Track warranties for equipment",
     "t_codes": ["IE02"], "category": "master-data"},
    {"id": "PM-016", "name": "Permit Management", "name_ja": "作業許可管理",
     "description": "Work permits and safety clearances",
     "t_codes": ["IW31"], "category": "execution"},
    {"id": "PM-017", "name": "Fleet Management", "name_ja": "車両管理",
     "description": "Vehicle and fleet maintenance tracking",
     "t_codes": ["IE01"], "category": "master-data"},
    {"id": "PM-018", "name": "Maintenance Reporting", "name_ja": "保全レポート",
     "description": "MTBF, MTTR, availability reports",
     "t_codes": ["IW65", "IW69"], "category": "reporting"},
    {"id": "PM-019", "name": "Pool Asset Management", "name_ja": "共用資産管理",
     "description": "Manage shared/pool equipment",
     "t_codes": ["IE01"], "category": "master-data"},
    {"id": "PM-020", "name": "Integration with PP/QM", "name_ja": "PP/QM連携",
     "description": "Integration with production and quality",
     "t_codes": ["IW31"], "category": "integration"},
]

# ---------------------------------------------------------------------------
# HR - Human Resources (人事管理)
# ---------------------------------------------------------------------------
HR_FUNCTIONS: list[dict[str, Any]] = [
    {"id": "HR-001", "name": "Organizational Management", "name_ja": "組織管理",
     "description": "Organizational structure and positions",
     "t_codes": ["PPOME", "PO10", "PO13"], "category": "org-mgmt"},
    {"id": "HR-002", "name": "Personnel Administration", "name_ja": "人事管理",
     "description": "Employee master data management",
     "t_codes": ["PA20", "PA30", "PA40"], "category": "personnel"},
    {"id": "HR-003", "name": "Hiring / Onboarding", "name_ja": "採用・入社処理",
     "description": "New employee hiring process",
     "t_codes": ["PA40"], "category": "personnel"},
    {"id": "HR-004", "name": "Personnel Actions", "name_ja": "人事措置",
     "description": "Promotions, transfers, terminations",
     "t_codes": ["PA40"], "category": "personnel"},
    {"id": "HR-005", "name": "Time Management", "name_ja": "勤怠管理",
     "description": "Work schedules, attendance, absences",
     "t_codes": ["PA61", "PA62", "PT01"], "category": "time"},
    {"id": "HR-006", "name": "Time Evaluation", "name_ja": "勤怠評価",
     "description": "Calculate overtime, bonuses based on time",
     "t_codes": ["PT60"], "category": "time"},
    {"id": "HR-007", "name": "Leave Management", "name_ja": "休暇管理",
     "description": "Leave entitlements, balances, requests",
     "t_codes": ["PA61"], "category": "time"},
    {"id": "HR-008", "name": "Payroll Processing", "name_ja": "給与計算",
     "description": "Gross-to-net payroll calculation",
     "t_codes": ["PC00_M99_RUN"], "category": "payroll"},
    {"id": "HR-009", "name": "Payroll Results", "name_ja": "給与結果管理",
     "description": "View and adjust payroll results",
     "t_codes": ["PC_PAYRESULT"], "category": "payroll"},
    {"id": "HR-010", "name": "Remuneration Statement", "name_ja": "給与明細",
     "description": "Generate and distribute pay slips",
     "t_codes": ["PC00_M99_CEDT"], "category": "payroll"},
    {"id": "HR-011", "name": "Benefits Management", "name_ja": "福利厚生管理",
     "description": "Employee benefits enrollment and tracking",
     "t_codes": ["HRBEN0001"], "category": "benefits"},
    {"id": "HR-012", "name": "Recruitment", "name_ja": "採用管理",
     "description": "Job postings, applicant tracking",
     "t_codes": ["PB10", "PB30"], "category": "recruitment"},
    {"id": "HR-013", "name": "Training and Event Management", "name_ja": "研修管理",
     "description": "Training catalog, attendance, scheduling",
     "t_codes": ["LSO_RHXKURS0"], "category": "development"},
    {"id": "HR-014", "name": "Performance Management", "name_ja": "人事考課",
     "description": "Appraisals and performance reviews",
     "t_codes": ["PHAP_ADMIN"], "category": "development"},
    {"id": "HR-015", "name": "Compensation Management", "name_ja": "報酬管理",
     "description": "Salary planning and compensation adjustments",
     "t_codes": ["PECM_MANAGE_COMP"], "category": "compensation"},
    {"id": "HR-016", "name": "Travel Management", "name_ja": "出張管理",
     "description": "Travel requests, expenses, reimbursement",
     "t_codes": ["PR05", "TRIP"], "category": "travel"},
    {"id": "HR-017", "name": "Employee Self-Service (ESS)", "name_ja": "従業員セルフサービス",
     "description": "Employee portal for time, leave, personal data",
     "t_codes": ["ESS"], "category": "self-service"},
    {"id": "HR-018", "name": "Manager Self-Service (MSS)", "name_ja": "管理者セルフサービス",
     "description": "Manager portal for approvals and team mgmt",
     "t_codes": ["MSS"], "category": "self-service"},
    {"id": "HR-019", "name": "HR Reporting", "name_ja": "人事レポート",
     "description": "Headcount, turnover, workforce analytics",
     "t_codes": ["S_AHR_61016380"], "category": "reporting"},
    {"id": "HR-020", "name": "Personnel Cost Planning", "name_ja": "人件費計画",
     "description": "Workforce cost planning and simulation",
     "t_codes": ["PT_BAL00"], "category": "planning"},
]

# ---------------------------------------------------------------------------
# Module Registry (モジュール登録)
# ---------------------------------------------------------------------------
SAP_MODULES: dict[str, dict[str, Any]] = {
    "SD": {
        "name": "Sales and Distribution",
        "name_ja": "販売管理",
        "description": "End-to-end sales process from quotation to billing",
        "description_ja": "見積→受注→出荷→請求の販売プロセス全体を管理",
        "standard_functions": SD_FUNCTIONS,
    },
    "MM": {
        "name": "Materials Management",
        "name_ja": "在庫/購買管理",
        "description": "Procurement and inventory management",
        "description_ja": "購買依頼→発注→入庫→請求照合の購買プロセスと在庫管理",
        "standard_functions": MM_FUNCTIONS,
    },
    "FI": {
        "name": "Financial Accounting",
        "name_ja": "財務会計",
        "description": "General ledger, AP, AR, asset accounting, bank",
        "description_ja": "総勘定元帳、買掛金、売掛金、固定資産、銀行会計",
        "standard_functions": FI_FUNCTIONS,
    },
    "CO": {
        "name": "Controlling",
        "name_ja": "管理会計",
        "description": "Cost center, profit center, internal orders, CO-PA",
        "description_ja": "原価センター、利益センター、内部指図、収益性分析",
        "standard_functions": CO_FUNCTIONS,
    },
    "PP": {
        "name": "Production Planning",
        "name_ja": "生産計画",
        "description": "Demand management, MRP, production orders",
        "description_ja": "需要管理→MRP→製造指図→完成確認の生産プロセス",
        "standard_functions": PP_FUNCTIONS,
    },
    "WM": {
        "name": "Warehouse Management",
        "name_ja": "倉庫管理",
        "description": "Warehouse operations from inbound to outbound",
        "description_ja": "入庫→在庫管理→出庫→棚卸の倉庫オペレーション",
        "standard_functions": WM_FUNCTIONS,
    },
    "QM": {
        "name": "Quality Management",
        "name_ja": "品質管理",
        "description": "Inspection, notification, quality control",
        "description_ja": "検査ロット→検査結果→品質通知の品質管理プロセス",
        "standard_functions": QM_FUNCTIONS,
    },
    "PM": {
        "name": "Plant Maintenance",
        "name_ja": "プラント保全",
        "description": "Equipment maintenance and asset management",
        "description_ja": "設備管理→保全計画→保全指図→保全実績の保全プロセス",
        "standard_functions": PM_FUNCTIONS,
    },
    "HR": {
        "name": "Human Resources",
        "name_ja": "人事管理",
        "description": "Organization, personnel, time, payroll management",
        "description_ja": "組織管理→人事管理→勤怠管理→給与計算",
        "standard_functions": HR_FUNCTIONS,
    },
}


def get_module(module_id: str) -> dict[str, Any] | None:
    """Get a SAP module definition by ID."""
    return SAP_MODULES.get(module_id.upper())


def get_all_modules() -> dict[str, dict[str, Any]]:
    """Get all SAP module definitions."""
    return SAP_MODULES


def get_module_summary() -> list[dict[str, str]]:
    """Get a summary list of all modules (without functions detail)."""
    return [
        {
            "id": mid,
            "name": m["name"],
            "name_ja": m["name_ja"],
            "description_ja": m["description_ja"],
            "function_count": str(len(m["standard_functions"])),
        }
        for mid, m in SAP_MODULES.items()
    ]


def get_functions_for_module(module_id: str) -> list[dict[str, Any]]:
    """Get standard functions for a specific module."""
    mod = SAP_MODULES.get(module_id.upper())
    if mod is None:
        return []
    return mod["standard_functions"]


def search_functions(keyword: str) -> list[dict[str, Any]]:
    """Search across all modules for functions matching a keyword."""
    keyword_lower = keyword.lower()
    results: list[dict[str, Any]] = []
    for mid, mod in SAP_MODULES.items():
        for func in mod["standard_functions"]:
            if (
                keyword_lower in func["name"].lower()
                or keyword_lower in func["name_ja"]
                or keyword_lower in func["description"].lower()
                or keyword_lower in func.get("category", "").lower()
            ):
                results.append({**func, "module": mid})
    return results
